config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  devise_for :users, controllers: { 
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    resources :plans, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :social_accounts, only: [:destroy]
    resource :profile, only: [:edit, :update]
    resource :notification, only: [:edit, :update]
    resource :password, only: [:new, :create, :edit, :password]
    patch "/password", to: "passwords#update"
    get "/plans_published", to: "plans#published"
    get "/plans_draft", to: "plans#draft"
    get "/suggest_spot", to: "plans#suggest_spot"
    post "/spots", to: "spots#create"
    post "/photos", to: "photos#create"
    get "/unsubscribe", to: "unsubscribe#show"
    patch "/level_up", to: "level_up#update"
    patch "/got_trophy", to: "got_trophy#update"
  end

  resources :users, module: :users, param: :name, path: "/", only: [] do
    resource :profile, only: [:show], controller: "profiles"
    get "/likes", to: "profiles#like"
    get "/trophies", to: "profiles#trophy"
    get "/followers", to: "profiles#followers"
    get "/following", to: "profiles#following"
    resource :relationship, only: [:create, :destroy]
  end

  resources :plans, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get "/search", to: "search#index"
  get "/terms", to: "static#terms"
  get "/privacy_policy", to: "static#privacy_policy"
  post "/opinions", to: "opinions#create"

  namespace :batch do
    resources :save_page_views, only: [:create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/concerns/user/level_countable.rb
module User::LevelCountable
  extend ActiveSupport::Concern

  LEVEL_TABLE = [
    # 1 ~ 10
    0, 10, 30, 60, 100, 150, 230, 350, 500, 700,
    # 11 ~ 20
    950, 1200, 1500, 1800, 2300, 2800, 3500, 4200, 5000, 6000,
    # 21 ~ 30
    7000, 8000, 10000, 13000, 16000, 20000, 25000, 30000, 36000, 42000,
    # 31 ~ 40
    48000, 54000, 60000, 70000, 80000, 90000, 100000, 115000, 130000, 145000,
  ]

  def obtain_exp!
    self.class.transaction do
      update!(exp: calc_exp + trophy.exp)
      level_up!
    end
  end

  def next_level_exp
    # 最大レベルまで達している場合は-1を返す
    LEVEL_TABLE[level] || -1
  end

  def next_level_exp_rate
    return 0 if exp <= current_level_exp

    ((exp - current_level_exp).to_f / (next_level_exp - current_level_exp) * 100).round(1)
  end

  private

    def calc_exp
      total = 0
      total += followers.length * 2
      plans.published.eager_load(:spots, :photos, :likes).each do |plan|
        total += plan.spots.length >= 5 ? 30 : 10
        total += plan.photos.length * 1
        # N+1問題の回避策としてwhereを使わない
        total += plan.likes.select { |like| like.user_id != plan.user_id }.length * 2
      end
      total
    end

    def level_up!
      # 上限経験値を越えている場合、レベルアップしない
      return false if LEVEL_TABLE.last <= exp
      return false if level >= next_level

      update!(level: next_level, level_up: true)
    end

    def next_level
      prev_threshold = 0
      LEVEL_TABLE.index do |threshold|
        next if threshold == prev_threshold

        if prev_threshold <= exp && exp < threshold
          true
        else
          prev_threshold = threshold
          false
        end
      end
    end

    def current_level_exp
      LEVEL_TABLE[level - 1]
    end
end

app/models/concerns/users/level_countable.rb
module Users::LevelCountable
  extend ActiveSupport::Concern

  LEVEL_TABLE = [
    # 1 ~ 10
    0, 10, 30, 60, 100, 150, 230, 350, 500, 700,
    # 11 ~ 20
    950, 1200, 1500, 1800, 2300, 2800, 3500, 4200, 5000, 6000,
    # 21 ~ 30
    7000, 8000, 10000, 13000, 16000, 20000, 25000, 30000, 36000, 42000,
    # 31 ~ 40
    48000, 54000, 60000, 70000, 80000, 90000, 100000, 115000, 130000, 145000,
  ]

  def obtain_exp!
    self.class.transaction do
      update!(exp: calc_exp + trophy.exp)
      level_up!
    end
  end

  def next_level_exp
    # 最大レベルまで達している場合は-1を返す
    LEVEL_TABLE[level] || -1
  end

  def next_level_exp_rate
    return 0 if exp <= current_level_exp

    ((exp - current_level_exp).to_f / (next_level_exp - current_level_exp) * 100).round(1)
  end

  private

    def calc_exp
      total = 0
      total += followers.length * 2
      plans.published.eager_load(:spots, :photos, :likes).each do |plan|
        total += plan.spots.length >= 5 ? 30 : 10
        total += plan.photos.length * 1
        # N+1問題の回避策としてwhereを使わない
        total += plan.likes.select { |like| like.user_id != plan.user_id }.length * 2
      end
      total
    end

    def level_up!
      # 上限経験値を越えている場合、レベルアップしない
      return false if LEVEL_TABLE.last <= exp
      return false if level >= next_level

      update!(level: next_level, level_up: true)
    end

    def next_level
      prev_threshold = 0
      LEVEL_TABLE.index do |threshold|
        next if threshold == prev_threshold

        if prev_threshold <= exp && exp < threshold
          true
        else
          prev_threshold = threshold
          false
        end
      end
    end

    def current_level_exp
      LEVEL_TABLE[level - 1]
    end
end

app/controllers/users/got_trophy_controller.rb
class Users::GotTrophyController < ApplicationController
  def update
    current_user.update!(got_trophy_name: nil)
    render status: 200, json: "ok"
  end
end

app/controllers/users/level_up_controller.rb
class Users::LevelUpController < ApplicationController
  def update
    current_user.update!(level_up: false)
    render status: 200, json: "ok"
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < ApplicationController
  before_action :set_notification

  def edit
  end

  def update
    @notification.update!(notification_paramas)
    redirect_to edit_users_notification_path, notice: t(:update_success, scope: :flash)
  end

  private

    def set_notification
      @notification = current_user.notification
    end

    def notification_paramas
      params.require(:notification).permit(:when_like, :when_comment, :when_follow, :when_news)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :authenticate_user!

  def twitter
    if user_signed_in?
      connect_to :twitter
    else
      callback_from :twitter
    end
  end

  private

    def callback_from(provider)
      provider = provider.to_s
      @user = User.find_for_oauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = t("devise.omniauth_callbacks.registered", kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      elsif User.find_by(email: @user.email).present?
        redirect_to new_user_session_path, alert: t("devise.omniauth_callbacks.already_registered", kind: provider.capitalize)
      elsif @user.present?
        flash.now[:notice] = t("devise.omniauth_callbacks.success", kind: provider.capitalize)
        render "users/registrations/new"
      else
        redirect_to new_user_registration_path, alert: t("devise.omniauth_callbacks.faild", kind: provider.capitalize)
      end
    end

    def connect_to(provider)
      provider = provider.to_s
      auth = request.env["omniauth.auth"]
      social_account = current_user.social_accounts.build(uid: auth.uid, provider: auth.provider, access_token: auth.credentials.token, access_secret: auth.credentials.secret)
      if social_account.save
        redirect_to edit_user_registration_path, notice: t("devise.omniauth_callbacks.success_connection", kind: provider.capitalize)
      else
        redirect_to edit_user_registration_path, alert: t("devise.omniauth_callbacks.already_used", kind: provider.capitalize)
      end
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
  before_action :set_current_user
  before_action :redirect_to_new_password, only: [:edit, :update]
  before_action :redirect_to_edit_password, only: [:new, :create]

  def new
  end

  def create
    if @user.update(new_password_params)
      bypass_sign_in(@user)
      redirect_to root_path, notice: t("flash.register_success")
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @user.extend(Devise::Models::DatabaseAuthenticatablePatch)
    if @user.update_with_password(password_params)
      bypass_sign_in(@user)
      redirect_to root_path, notice: t("flash.update_success")
    else
      render "edit"
    end
  end

  private

    def set_current_user
      @user = current_user
    end

    def new_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def password_params
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end

    def redirect_to_new_password
      redirect_to new_users_password_path if current_user.encrypted_password.blank?
    end

    def redirect_to_edit_password
      redirect_to edit_users_password_path if current_user.encrypted_password.present?
    end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  def create
    spot = Spot.find(params[:spot_id].to_i)
    photo = spot.photos.build(photo_params)
    if photo.save
      render json: { photo: photo, status: "OK" }
    else
      message = photo.errors.full_messages
      render json: { message: message, status: "INVALID" }
    end
  end

  private

    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/users/plans_controller.rb
class Users::PlansController < ApplicationController
  before_action :set_plan, only: [:edit, :update, :destroy]
  before_action :is_current_user?, only: [:edit, :update, :destroy]

  def index
    @plans = current_user.plans.management_order.page(params[:page])
    respond_to do |format|
      format.html
      format.js { render "plan_list" }
    end
  end

  def published
    @plans = current_user.plans.published.management_order.page(params[:page])
    respond_to do |format|
      format.js { render "plan_list" }
    end
  end

  def draft
    @plans = current_user.plans.draft.management_order.page(params[:page])
    respond_to do |format|
      format.js { render "plan_list" }
    end
  end

  def new
    @plan = current_user.plans.build
  end

  def create
    @plan = current_user.plans.build(new_plan_params)
    if @plan.save
      redirect_to edit_users_plan_path(@plan, init: true)
    else
      render "new"
    end
  end

  def edit
    @plan.spots.create if @plan.spots.blank?
  end

  def update
    if params[:published]
      @plan.status = :published
      @plan.published_at = Time.zone.now if @plan.published_at.blank?
    elsif params[:draft]
      @plan.status = :draft
    end

    if @plan.update(edit_plan_params)
      if params[:sortable]
        redirect_to edit_users_plan_path(@plan), notice: t(:sort_success, scope: :flash)
      else
        RefreshSitemapJob.perform_later
        current_user.obtain_exp!
        current_user.trophy.judge_plan_count!
        redirect_to plan_path(@plan), notice: t(:update_success, scope: :flash)
      end
    else
      flash.now[:alert] = t(:register_failed, scope: :flash)
      render "edit"
    end
  end

  def destroy
    @plan.destroy!
    @plan.user.obtain_exp!
    redirect_to users_plans_path, notice: t(:delete_success, scope: :flash)
  end

  def suggest_spot
    key = Rails.configuration.x.google_apis[:map]
    input = params[:input]

    # オートコンプリート用のクエリ
    url = "https://maps.googleapis.com/maps/api/place/autocomplete/json?"
    params = URI.encode_www_form({ key: key, input: input, language: :ja})
    uri = URI.parse "#{url}#{params}"

    request = Net::HTTP::Get.new(uri.request_uri)
    response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") do |http|
      http.request(request)
    end

    body = JSON.load response.body
    places = body["predictions"].map do |item|
      {
        place_id: item.dig("place_id"),
        name: item.dig("structured_formatting", "main_text"),
        address: item.dig("structured_formatting", "secondary_text"),
      }
    end

    render json: places
  end

  private

    def new_plan_params
      params.require(:plan).permit(:name, :description)
    end

    def edit_plan_params
      params.require(:plan).permit(:name, :description, spots_attributes: [:id, :name, :description, :address, :latitude, :longitude, :position, :_destroy, photos_attributes: [:id, :position, :is_header, :_destroy]])
    end

    def set_plan
      @plan = current_user.plans.find(params[:id])
    end

    def is_current_user?
      redirect_to root_path unless @plan.user == current_user
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :like, :trophy, :followers, :following]
  before_action :set_user, only: [:show, :like, :trophy, :followers, :following]
  before_action :set_profile, only: [:edit, :update]
  before_action :set_meta, only: [:show]

  def show
    @plans = @user.plans.published
  end

  def like
    @plans = @user.liked_plans
    render :show
  end

  def trophy
    @trophy = @user.trophy
  end

  def followers
    @follow_users = @user.followers.order(created_at: :desc)
    render :follow_list
  end

  def following
    @follow_users = @user.following.order(created_at: :desc)
    render :follow_list
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to user_profile_path(current_user.name), notice: t("flash.update_success")
    else
      render "edit"
    end
  end

  private

    def profile_params
      params.require(:profile).permit(:name, :description, :location, :url, :gender, :birthday, :image)
    end

    def set_user
      @user = User.find_by!(name: params[:user_name])
    end

    def set_profile
      @profile = current_user.profile
    end

    def set_meta
      case action_name
      when "show"
        title = @user.profile.name.present? ? "#{@user.profile.name}さん" : "#{@user.name}さん"
        set_common_meta(:title, title)
        set_common_meta(:description, @user.profile.description) if @user.profile.description.present?
        set_common_meta(:image, @user.profile_image_url) if @user.profile.image.present?
      end
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

    def after_sign_up_path_for(resource)
      edit_users_profile_path(init: true)
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  def create
    follower = User.find_by!(name: params[:user_name])
    ActiveRecord::Base.transaction do
      current_user.follow!(follower)
      follower.obtain_exp!
      follower.trophy.judge_follower_count!
    end
    FollowMailer.email(follower).deliver if follower.notification.when_follow?
    redirect_back fallback_location: user_profile_path(follower.name), notice: "#{follower.display_name}さんをフォローしました"
  end

  def destroy
    follower = User.find_by!(name: params[:user_name])
    ActiveRecord::Base.transaction do
      current_user.unfollow!(follower)
      follower.obtain_exp!
    end
    redirect_back fallback_location: user_profile_path(follower.name), notice: "#{follower.display_name}さんのフォローを解除しました"
  end
end

app/controllers/users/social_accounts_controller.rb
class Users::SocialAccountsController < ApplicationController
  def destroy
    social_account = SocialAccount.find(params[:id])
    social_account.destroy!
    redirect_to edit_user_registration_path, notice: t("devise.omniauth_callbacks.release_connection", kind: social_account.provider.capitalize)
  end
end

app/controllers/users/spots_controller.rb
class Users::SpotsController < ApplicationController
  def create
    plan = Plan.find(params[:plan_id])
    @spot = plan.spots.create(position: params[:position])
    render json: @spot.id
  end
end

app/controllers/users/unsubscribe_controller.rb
class Users::UnsubscribeController < ApplicationController
  def show
  end
end

app/views/users/profiles/_form.html.haml
= simple_form_for @profile, url: users_profile_path do |f|
  .image-field
    = f.input :image, as: :image_preview, input_html: { class: "images" }
  = f.input :name, hint: t("form.profile_name_hint", user_name: @profile.user.name)
  = f.input :description, input_html: { rows: 4 }
  = f.input :location, placeholder: "#{t('view.example')}#{t('.location_example')}"
  = f.input :url, placeholder: "#{t('view.example')}#{root_url}"
  = f.input :gender, include_blank: t("form.select_item", item: Profile.human_attribute_name(:gender)), class: "form-control"
  = f.input :birthday, use_month_numbers: true,
            start_year: Date.today.year,
            end_year: Date.today.year - 110,
            prompt: ["年", "月", "日"],
            input_html: { class: "profile-birthday" }
  = f.button :submit, class: "btn-success btn-100"

app/views/users/profiles/_plan_list.html.haml
- if plans.present?
  = render "shared/plan_index_group", plans: plans, size: "sm"
- else
  = t("view.no_plans")

app/views/users/profiles/_profile.html.haml
.profile-area.col-lg-3.col-sm-4
  .profile-image
    = image_tag profile.image_url.presence || "no_user_image.svg"
  %h3.profile-name= user.display_name
  - if current_user && user != current_user
    - if current_user.following?(user)
      = link_to "フォロー中", user_relationship_path(user.name), method: :delete, class: "btn btn-success btn-block", data: { disable_with: "処理中..." }
    - else
      = link_to "フォローする", user_relationship_path(user.name), method: :post, class: "btn btn-default btn-block", data: { disable_with: "処理中..." }
  .d-flex
    .profile-level-area
      .profile-level
        %span.level-title Lv.
        %span.level-value= user.level
      .profile-exp= "Exp #{user.exp}/#{user.next_level_exp}"
    .profile-exp-rate
      .bar-chart{ style: "width: #{user.next_level_exp_rate}%;" }
  .profile-description= profile.description
  - if profile.location.present?
    .profile-item
      = fa_icon "map-pin"
      = profile.location
  - if profile.url.present?
    .profile-item{ style: "word-break: break-all;" }
      = fa_icon "link"
      = link_to url_without_protocol(profile.url), profile.url, target: "_blank"
  - if profile.gender.present?
    .profile-item
      = fa_icon "user-circle-o"
      = profile.gender_text
  - if profile.birthday.present?
    .profile-item
      = fa_icon "birthday-cake"
      = l(profile.birthday, format: :long)
  - if user == current_user
    %p= link_to t("link.edit_profile"), edit_users_profile_path, class: "btn btn-success"

app/views/users/profiles/_profile_menu.html.haml
%ul.plan-status-menu
  %li= link_to t(".least_plans"), user_profile_path(user.name), class: "#{'active' if action_name == 'show'}"
  %li= link_to t(".liked_plans"), user_likes_path(user.name), class: "#{'active' if action_name == 'like'}"
  %li
    = link_to user_followers_path(user.name), class: "#{'active' if action_name == 'followers'}" do
      %span= t(".followers")
      %span.badge= user.followers.length
  %li
    = link_to user_following_path(user.name), class: "#{'active' if action_name == 'following'}" do
      %span= t(".following")
      %span.badge= user.following.length
  %li= link_to t(".trophy"), user_trophies_path(user.name), class: "#{'active' if action_name == 'trophy'}"

app/views/users/profiles/edit.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .register-form
        - if params[:init].present?
          .registration-step
            %h3= t("view.registration_step")
            %span.text-muted= t("view.suggestion_register_profile")
            = link_to t("link.skip_profile"), root_path
        - else
          %h3= t(".title")
        = render "form"

app/views/users/profiles/follow_list.html.haml
.container
  .row
    = render "profile", profile: @user.profile, user: @user
    .plan-index-area.col-lg-9.col-sm-8
      .plan-index-group
        = render "profile_menu", user: @user
        %ul.follow-user-list
          - @follow_users.each do |follow_user|
            %li.follow-user
              .item-left
                .follow-user-image
                  = image_tag follow_user.profile_image_thumb_url
              .item-right
                .item-main
                  .follow-user-name
                    = link_to follow_user.display_name, user_profile_path(follow_user.name)
                  .follow-user-follow-button
                    - if current_user.following?(follow_user)
                      = link_to "フォロー中", user_relationship_path(follow_user.name), method: :delete, class: "btn btn-success btn-sm", data: { disable_with: "処理中..." }
                    - else
                      = link_to "フォローする", user_relationship_path(follow_user.name), method: :post, class: "btn btn-default btn-sm", data: { disable_with: "処理中..." }
                .item-sub
                  .follow-user-description
                    = follow_user.profile.description

app/views/users/profiles/show.html.haml
.container
  .row
    = render "profile", profile: @user.profile, user: @user
    .plan-index-area.col-lg-9.col-sm-8
      .plan-index-group
        = render "profile_menu", user: @user
        .plan-list
          = render "plan_list", plans: @plans

app/views/users/profiles/trophy.html.haml
.container
  .row
    = render "profile", profile: @user.profile, user: @user
    .plan-index-area.col-lg-9.col-sm-8
      .plan-index-group
        = render "profile_menu", user: @user
        .trophy-list
          - Trophy.titles.each do |title|
            .trophy-item
              .text-center= image_tag @trophy.send(title) ? "trophy.png" : "no_trophy.png",
                            title: "ボーナスExp: #{Trophy.const_get("#{title.upcase}_EXP")}", class: "trophy-image"
              .trophy-title.text-center= Trophy.human_attribute_name title
              .trophy-desc.text-center= Trophy.human_attribute_name "#{title}_desc"