config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  devise_for :users, controllers: { 
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    resources :plans, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :social_accounts, only: [:destroy]
    resource :profile, only: [:edit, :update]
    resource :notification, only: [:edit, :update]
    resource :password, only: [:new, :create, :edit, :password]
    patch "/password", to: "passwords#update"
    get "/plans_published", to: "plans#published"
    get "/plans_draft", to: "plans#draft"
    get "/suggest_spot", to: "plans#suggest_spot"
    post "/spots", to: "spots#create"
    post "/photos", to: "photos#create"
    get "/unsubscribe", to: "unsubscribe#show"
    patch "/level_up", to: "level_up#update"
    patch "/got_trophy", to: "got_trophy#update"
  end

  resources :users, module: :users, param: :name, path: "/", only: [] do
    resource :profile, only: [:show], controller: "profiles"
    get "/likes", to: "profiles#like"
    get "/trophies", to: "profiles#trophy"
    get "/followers", to: "profiles#followers"
    get "/following", to: "profiles#following"
    resource :relationship, only: [:create, :destroy]
  end

  resources :plans, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get "/search", to: "search#index"
  get "/terms", to: "static#terms"
  get "/privacy_policy", to: "static#privacy_policy"
  post "/opinions", to: "opinions#create"

  namespace :batch do
    resources :save_page_views, only: [:create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/concerns/user/level_countable.rb
module User::LevelCountable
  extend ActiveSupport::Concern

  LEVEL_TABLE = [
    # 1 ~ 10
    0, 10, 30, 60, 100, 150, 230, 350, 500, 700,
    # 11 ~ 20
    950, 1200, 1500, 1800, 2300, 2800, 3500, 4200, 5000, 6000,
    # 21 ~ 30
    7000, 8000, 10000, 13000, 16000, 20000, 25000, 30000, 36000, 42000,
    # 31 ~ 40
    48000, 54000, 60000, 70000, 80000, 90000, 100000, 115000, 130000, 145000,
  ]

  def obtain_exp!
    self.class.transaction do
      update!(exp: calc_exp + trophy.exp)
      level_up!
    end
  end

  def next_level_exp
    # 最大レベルまで達している場合は-1を返す
    LEVEL_TABLE[level] || -1
  end

  def next_level_exp_rate
    return 0 if exp <= current_level_exp

    ((exp - current_level_exp).to_f / (next_level_exp - current_level_exp) * 100).round(1)
  end

  private

    def calc_exp
      total = 0
      total += followers.length * 2
      plans.published.eager_load(:spots, :photos, :likes).each do |plan|
        total += plan.spots.length >= 5 ? 30 : 10
        total += plan.photos.length * 1
        # N+1問題の回避策としてwhereを使わない
        total += plan.likes.select { |like| like.user_id != plan.user_id }.length * 2
      end
      total
    end

    def level_up!
      # 上限経験値を越えている場合、レベルアップしない
      return false if LEVEL_TABLE.last <= exp
      return false if level >= next_level

      update!(level: next_level, level_up: true)
    end

    def next_level
      prev_threshold = 0
      LEVEL_TABLE.index do |threshold|
        next if threshold == prev_threshold

        if prev_threshold <= exp && exp < threshold
          true
        else
          prev_threshold = threshold
          false
        end
      end
    end

    def current_level_exp
      LEVEL_TABLE[level - 1]
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_plan, only: [:show]
  before_action :set_meta

  def index
    case params[:type]
    when "popular"
      @plans = Plan.with_popular.page(params[:page])
    when "following"
      @plans = current_user.following_plans.page(params[:page]) if user_signed_in?
    else
      @plans = Plan.published.page(params[:page])
    end
  end

  def show
    @user = @plan.user
    return redirect_to root_path if @plan.draft? && @user != current_user

    @plan.increment_pv if @user != current_user
    @user.trophy.judge_pv_count!

    @photo = @plan.get_header_image
    @like = @plan.likes.find_by(user: current_user)
    @comment = current_user&.comments&.build
    @comments = @plan.comments
  end

  private

    def set_plan
      @plan = Plan.find(params[:id])
    end

    def set_meta
      case action_name
      when "index" then
        title = params[:type] == "popular" ? t(".popular_plans") : t(".latest_plans")
        set_common_meta(:title, title)
      when "show" then
        set_common_meta(:title, @plan.name)
        set_common_meta(:description, @plan.description)
        set_common_meta(:image, @plan.get_header_image.image.url) if @plan.get_header_image.present?
        set_meta_tags keyword: @plan.spots.map(&:name).join(", ")
      end
    end
end

app/controllers/users/got_trophy_controller.rb
class Users::GotTrophyController < ApplicationController
  def update
    current_user.update!(got_trophy_name: nil)
    render status: 200, json: "ok"
  end
end

app/controllers/users/level_up_controller.rb
class Users::LevelUpController < ApplicationController
  def update
    current_user.update!(level_up: false)
    render status: 200, json: "ok"
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < ApplicationController
  before_action :set_notification

  def edit
  end

  def update
    @notification.update!(notification_paramas)
    redirect_to edit_users_notification_path, notice: t(:update_success, scope: :flash)
  end

  private

    def set_notification
      @notification = current_user.notification
    end

    def notification_paramas
      params.require(:notification).permit(:when_like, :when_comment, :when_follow, :when_news)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :authenticate_user!

  def twitter
    if user_signed_in?
      connect_to :twitter
    else
      callback_from :twitter
    end
  end

  private

    def callback_from(provider)
      provider = provider.to_s
      @user = User.find_for_oauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = t("devise.omniauth_callbacks.registered", kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      elsif User.find_by(email: @user.email).present?
        redirect_to new_user_session_path, alert: t("devise.omniauth_callbacks.already_registered", kind: provider.capitalize)
      elsif @user.present?
        flash.now[:notice] = t("devise.omniauth_callbacks.success", kind: provider.capitalize)
        render "users/registrations/new"
      else
        redirect_to new_user_registration_path, alert: t("devise.omniauth_callbacks.faild", kind: provider.capitalize)
      end
    end

    def connect_to(provider)
      provider = provider.to_s
      auth = request.env["omniauth.auth"]
      social_account = current_user.social_accounts.build(uid: auth.uid, provider: auth.provider, access_token: auth.credentials.token, access_secret: auth.credentials.secret)
      if social_account.save
        redirect_to edit_user_registration_path, notice: t("devise.omniauth_callbacks.success_connection", kind: provider.capitalize)
      else
        redirect_to edit_user_registration_path, alert: t("devise.omniauth_callbacks.already_used", kind: provider.capitalize)
      end
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
  before_action :set_current_user
  before_action :redirect_to_new_password, only: [:edit, :update]
  before_action :redirect_to_edit_password, only: [:new, :create]

  def new
  end

  def create
    if @user.update(new_password_params)
      bypass_sign_in(@user)
      redirect_to root_path, notice: t("flash.register_success")
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @user.extend(Devise::Models::DatabaseAuthenticatablePatch)
    if @user.update_with_password(password_params)
      bypass_sign_in(@user)
      redirect_to root_path, notice: t("flash.update_success")
    else
      render "edit"
    end
  end

  private

    def set_current_user
      @user = current_user
    end

    def new_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def password_params
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end

    def redirect_to_new_password
      redirect_to new_users_password_path if current_user.encrypted_password.blank?
    end

    def redirect_to_edit_password
      redirect_to edit_users_password_path if current_user.encrypted_password.present?
    end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  def create
    spot = Spot.find(params[:spot_id].to_i)
    photo = spot.photos.build(photo_params)
    if photo.save
      render json: { photo: photo, status: "OK" }
    else
      message = photo.errors.full_messages
      render json: { message: message, status: "INVALID" }
    end
  end

  private

    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/users/plans_controller.rb
class Users::PlansController < ApplicationController
  before_action :set_plan, only: [:edit, :update, :destroy]
  before_action :is_current_user?, only: [:edit, :update, :destroy]

  def index
    @plans = current_user.plans.management_order.page(params[:page])
    respond_to do |format|
      format.html
      format.js { render "plan_list" }
    end
  end

  def published
    @plans = current_user.plans.published.management_order.page(params[:page])
    respond_to do |format|
      format.js { render "plan_list" }
    end
  end

  def draft
    @plans = current_user.plans.draft.management_order.page(params[:page])
    respond_to do |format|
      format.js { render "plan_list" }
    end
  end

  def new
    @plan = current_user.plans.build
  end

  def create
    @plan = current_user.plans.build(new_plan_params)
    if @plan.save
      redirect_to edit_users_plan_path(@plan, init: true)
    else
      render "new"
    end
  end

  def edit
    @plan.spots.create if @plan.spots.blank?
  end

  def update
    if params[:published]
      @plan.status = :published
      @plan.published_at = Time.zone.now if @plan.published_at.blank?
    elsif params[:draft]
      @plan.status = :draft
    end

    if @plan.update(edit_plan_params)
      if params[:sortable]
        redirect_to edit_users_plan_path(@plan), notice: t(:sort_success, scope: :flash)
      else
        RefreshSitemapJob.perform_later
        current_user.obtain_exp!
        current_user.trophy.judge_plan_count!
        redirect_to plan_path(@plan), notice: t(:update_success, scope: :flash)
      end
    else
      flash.now[:alert] = t(:register_failed, scope: :flash)
      render "edit"
    end
  end

  def destroy
    @plan.destroy!
    @plan.user.obtain_exp!
    redirect_to users_plans_path, notice: t(:delete_success, scope: :flash)
  end

  def suggest_spot
    key = Rails.configuration.x.google_apis[:map]
    input = params[:input]

    # オートコンプリート用のクエリ
    url = "https://maps.googleapis.com/maps/api/place/autocomplete/json?"
    params = URI.encode_www_form({ key: key, input: input, language: :ja})
    uri = URI.parse "#{url}#{params}"

    request = Net::HTTP::Get.new(uri.request_uri)
    response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") do |http|
      http.request(request)
    end

    body = JSON.load response.body
    places = body["predictions"].map do |item|
      {
        place_id: item.dig("place_id"),
        name: item.dig("structured_formatting", "main_text"),
        address: item.dig("structured_formatting", "secondary_text"),
      }
    end

    render json: places
  end

  private

    def new_plan_params
      params.require(:plan).permit(:name, :description)
    end

    def edit_plan_params
      params.require(:plan).permit(:name, :description, spots_attributes: [:id, :name, :description, :address, :latitude, :longitude, :position, :_destroy, photos_attributes: [:id, :position, :is_header, :_destroy]])
    end

    def set_plan
      @plan = current_user.plans.find(params[:id])
    end

    def is_current_user?
      redirect_to root_path unless @plan.user == current_user
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :like, :trophy, :followers, :following]
  before_action :set_user, only: [:show, :like, :trophy, :followers, :following]
  before_action :set_profile, only: [:edit, :update]
  before_action :set_meta, only: [:show]

  def show
    @plans = @user.plans.published
  end

  def like
    @plans = @user.liked_plans
    render :show
  end

  def trophy
    @trophy = @user.trophy
  end

  def followers
    @follow_users = @user.followers.order(created_at: :desc)
    render :follow_list
  end

  def following
    @follow_users = @user.following.order(created_at: :desc)
    render :follow_list
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to user_profile_path(current_user.name), notice: t("flash.update_success")
    else
      render "edit"
    end
  end

  private

    def profile_params
      params.require(:profile).permit(:name, :description, :location, :url, :gender, :birthday, :image)
    end

    def set_user
      @user = User.find_by!(name: params[:user_name])
    end

    def set_profile
      @profile = current_user.profile
    end

    def set_meta
      case action_name
      when "show"
        title = @user.profile.name.present? ? "#{@user.profile.name}さん" : "#{@user.name}さん"
        set_common_meta(:title, title)
        set_common_meta(:description, @user.profile.description) if @user.profile.description.present?
        set_common_meta(:image, @user.profile_image_url) if @user.profile.image.present?
      end
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

    def after_sign_up_path_for(resource)
      edit_users_profile_path(init: true)
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  def create
    follower = User.find_by!(name: params[:user_name])
    ActiveRecord::Base.transaction do
      current_user.follow!(follower)
      follower.obtain_exp!
      follower.trophy.judge_follower_count!
    end
    FollowMailer.email(follower).deliver if follower.notification.when_follow?
    redirect_back fallback_location: user_profile_path(follower.name), notice: "#{follower.display_name}さんをフォローしました"
  end

  def destroy
    follower = User.find_by!(name: params[:user_name])
    ActiveRecord::Base.transaction do
      current_user.unfollow!(follower)
      follower.obtain_exp!
    end
    redirect_back fallback_location: user_profile_path(follower.name), notice: "#{follower.display_name}さんのフォローを解除しました"
  end
end

app/controllers/users/social_accounts_controller.rb
class Users::SocialAccountsController < ApplicationController
  def destroy
    social_account = SocialAccount.find(params[:id])
    social_account.destroy!
    redirect_to edit_user_registration_path, notice: t("devise.omniauth_callbacks.release_connection", kind: social_account.provider.capitalize)
  end
end

app/controllers/users/spots_controller.rb
class Users::SpotsController < ApplicationController
  def create
    plan = Plan.find(params[:plan_id])
    @spot = plan.spots.create(position: params[:position])
    render json: @spot.id
  end
end

app/controllers/users/unsubscribe_controller.rb
class Users::UnsubscribeController < ApplicationController
  def show
  end
end

app/views/users/plans/_form.html.haml
.row
  = simple_form_for @plan, url: url, html: { class: "form-with-limit" } do |f|
    .col-md-9.main-field
      .register-form
        %h3= t(".title")
        = render "shared/input_with_limit", f: f, col: :name, limit: 100, rows: nil, hint: t("form.plan_name_hint")
        = render "shared/input_with_limit", f: f, col: :description, limit: 1000, rows: 5, hint: t("form.plan_description_hint")
      .spot-container
        %h3= t("form.register_spot")
        .spot-field
          = f.simple_fields_for :spots do |spot|
            = render "spot_fields", f: spot
          = button_tag type: :button, class: "btn btn-lg btn-success create-spot-btn", data: new_spot_field(f) do
            = fa_icon "plus-circle"
            = t("form.create_spot")
          .text-danger.map-rule= t("form.map_rule")
          .text-danger.no-routes{ style: "display: none;" }
            = t("form.no_routes")
          .map
    .col-md-3.sidebar
      .following-scroll
        .menu-box
          .menu-box-header
            = t("form.sortable_spots")
          .menu-box-body
            = t("form.help_sort")
          .menu-box-footer
            = f.button :submit, class: "submit-sortable", name: :sortable, style: "display: none"
            = button_tag t("form.sort"), type: :button, class: "btn btn-success sortable-spot-btn"
        .menu-box
          .menu-box-header
            = t("form.save_plan")
          .menu-box-body
            = t("form.help_save")
          .menu-box-footer
            = f.button :submit, t("form.published"), class: "btn-success published-btn", name: :published, style: "#{'display: none;' if @plan.draft? && params[:init].blank?}"
            = f.button :submit, t("form.draft"), class: "btn-success draft-btn", name: :draft, style: "#{'display: none;' if @plan.published? || params[:init].present?}"
            .dropdown.toggle-status
              = link_to "javascript:void(0);", class: "btn btn-success toggle-status-btn", data: { toggle: :dropdown } do
                = fa_icon "angle-down"
              %ul.dropdown-menu.toggle-menu{ style: "left: #{@plan.draft? ? '-132px' : '-120px'}" }
                %li.toggle-item
                  = link_to "javascript:void(0);", class: "set-published" do
                    = t("form.published")
                    = fa_icon "check", class: "toggle-check", style: "#{'display: none;' if @plan.draft? && params[:init].blank?}"
                %li.toggle-item
                  = link_to "javascript:void(0);", class: "set-draft" do
                    = t("form.draft")
                    = fa_icon "check", class: "toggle-check", style: "#{'display: none;' if @plan.published? || params[:init].present?}"

app/views/users/plans/_photo_fields.html.haml
.col-sm-4.photo-item
  = f.hidden_field :id, class: "photo-id"
  = f.hidden_field :position, class: "photo-position"
  = f.hidden_field :is_header, class: "photo-is-header"
  = f.hidden_field :_destroy, class: "photo-destroy"
  = image_tag f.object.image.present? ? f.object.image.thumb.url : "", class: "preview-photo #{"header-image" if f.object.is_header?}"
  = fa_stacked_icon "times-circle 2x",base: "circle inverse 2x", class: "destroy-photo-btn"
  = link_to t("form.set_header_image"), "javascript:void(0);", class: "btn btn-xs btn-success set-header-btn", style: "#{"display: none;" if f.object.is_header?}"

app/views/users/plans/_plan_list.html.haml
.table-responsive
  %table.table
    %thead
      %tr.plan-item
        %th.h-plan-title= t("view.plan_name")
        %th.h-plan-spot-count= t("view.spot_count")
        %th.h-plan-pvs= t("view.plan_pvs")
        %th.h-plan-likes= t("view.plan_likes")
        %th.h-plan-comments= t("view.plan_comments")
        %th.h-plan-created-at= t("view.plan_created_at")
        %th.h-plan-menu
    %tbody
      - if @plans.present?
        - @plans.each do |plan|
          %tr.plan-item
            %td.plan-title
              %h3.plan-name
                = link_to plan.name, plan_path(plan)
              .plan-status{ class: plan.status }
                = plan.status_text
              .plan-description
                = plan.description.truncate(100)
            %td.plan-spot-count
              = plan.spots.count
            %td.plan-pvs
              = plan.total_pv
            %td.plan-likes
              = plan.likes.count
            %td.plan-comments
              = plan.comments.count
            %td.plan-created-at
              = l plan.created_at, format: :long
            %td.plan-menu
              = link_to t("link.edit"), edit_users_plan_path(plan), class: "btn btn-success"
      - else
        %tr.plan-item
          %td.plan-title= t("view.no_plans")
          %td.plan-spot-count -
          %td.plan-pvs -
          %td.plan-likes -
          %td.plan-comments -
          %td.plan-created-at -

app/views/users/plans/_spot_fields.html.haml
.spot-form.jumbotron
  = f.hidden_field :id, class: "spot-field-id"
  = f.hidden_field :_destroy, class: "spot-destroy"
  = f.hidden_field :address, class: "spot-address"
  = f.hidden_field :latitude, class: "spot-latitude"
  = f.hidden_field :longitude, class: "spot-longitude"
  = f.hidden_field :position, class: "spot-position"
  = hidden_field_tag :place_id, "", class: "place-id"
  .form-group{ class: "#{'has-error' if f.object.errors.full_messages_for(:name).present?}" }
    .spot-position-num= f.object.position
    = f.text_field :name, placeholder: t("form.spot_name_hint"), class: "form-control spot-name", autocomplete: "nope"
    = render "shared/has_error", f: f, col: :name
  - if f.object.latitude.blank?
    .text-danger.preview-maps-rule= t("form.preview_maps_rule")
  .preview-maps
  .row.flex.photo-field
    = f.simple_fields_for :photos do |photo_f|
      = render "photo_fields", f: photo_f
    .col-sm-4.col-xs-12.photo-loading
      .loading-wrap
        = image_tag "oval.svg", class: "loading-icon"
    .col-sm-4.photo-input
      = file_field :photo, :image, multiple: true, class: "spot-photos", style: "display: none", data: new_photo_field(f)
      = image_tag "add_photos.png", class: "add-photos"
  = render "shared/input_with_limit", f: f, col: :description, limit: 1000, rows: 4, hint: t("form.spot_description_hint")
  = link_to t("form.destroy_spot"), "javascript:void(0);", class: "text-muted destroy-spot-btn"
  .clear

app/views/users/plans/edit.html.haml
.container
  = render "form", url: users_plan_path(@plan)
.sortable-modal
  .modal.fade
    .modal-dialog
      .modal-content
        .modal-header= t("form.sortable_spots")
        .modal-body
        .modal-footer
          = button_tag t("form.cancel"),  type: :button, class: "btn btn-danger", data: { dismiss: "modal" }
          = button_tag t("form.confirm"), type: :button, class: "btn btn-success confirm-sortable-btn"
.error-modal
  .modal.fade
    .modal-dialog
      .modal-content
        .modal-header= t("form.upload_error")
        .modal-body.text-danger
          .error-header
          %ul.error-body

app/views/users/plans/index.html.haml
.container
  %h2= t(".title")
  %ul.plan-status-menu
    %li= link_to t("view.status_all"), users_plans_path, remote: true, class: "active"
    %li= link_to t("view.published"), users_plans_published_path, remote: true
    %li= link_to t("view.draft"), users_plans_draft_path, remote: true
  .plan-list
    = render "plan_list"
  = paginate @plans

app/views/users/plans/new.html.haml
.container
  .col-md-8.col-md-offset-2
    .register-form
      %h3= t(".title")
      = simple_form_for @plan, url: users_plans_path, html: { class: "form-with-limit"} do |f|
        = render "shared/input_with_limit", f: f, col: :name, limit: 100, rows: nil, hint: t("form.plan_name_hint")
        = render "shared/input_with_limit", f: f, col: :description, limit: 1000, rows: 5, hint: t("form.plan_description_hint")
        = f.button :submit, t("form.register_plan"), class: "btn-success btn-100"

app/views/users/plans/plan_list.js.haml
:plain
  $(".plan-list").html("#{j(render 'users/plans/plan_list')}");