config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  devise_for :users, controllers: { 
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    resources :plans, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :social_accounts, only: [:destroy]
    resource :profile, only: [:edit, :update]
    resource :notification, only: [:edit, :update]
    resource :password, only: [:new, :create, :edit, :password]
    patch "/password", to: "passwords#update"
    get "/plans_published", to: "plans#published"
    get "/plans_draft", to: "plans#draft"
    get "/suggest_spot", to: "plans#suggest_spot"
    post "/spots", to: "spots#create"
    post "/photos", to: "photos#create"
    get "/unsubscribe", to: "unsubscribe#show"
    patch "/level_up", to: "level_up#update"
    patch "/got_trophy", to: "got_trophy#update"
  end

  resources :users, module: :users, param: :name, path: "/", only: [] do
    resource :profile, only: [:show], controller: "profiles"
    get "/likes", to: "profiles#like"
    get "/trophies", to: "profiles#trophy"
    get "/followers", to: "profiles#followers"
    get "/following", to: "profiles#following"
    resource :relationship, only: [:create, :destroy]
  end

  resources :plans, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get "/search", to: "search#index"
  get "/terms", to: "static#terms"
  get "/privacy_policy", to: "static#privacy_policy"
  post "/opinions", to: "opinions#create"

  namespace :batch do
    resources :save_page_views, only: [:create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_count_limit.html.haml
- count_limit = limit - (f.object.send(col)&.length || 0)
.limit-field{ class: "#{'text-danger' if count_limit < 0}" }
  = t("view.limit")
  %span.limit-value= count_limit
  = t("view.chars")

app/views/shared/_has_error.html.haml
- if f.object.errors[col].present?
  - f.object.errors.full_messages_for(col).each do |message|
    %span.help-block= message

app/views/shared/_input_with_limit.html.haml
.form-group{ class: "#{'has-error' if f.object.errors[col].present?}" }
  = f.label col
  = render "shared/count_limit", f: f, col: col, limit: limit
  = f.input_field col, rows: rows, class: "form-control limit-target", data: { limit: limit }
  = f.hint hint if hint.present?
  = render "shared/has_error", f: f, col: col

app/views/shared/_menu_bar.html.haml
.menu-box
  .menu-box-header
    = t("menu.setting_menu")
  .menu-box-body
    %ul
      %li{ class: "#{'active' if request.url == edit_user_registration_url}" }
        = link_to t("menu.user_info"), edit_user_registration_path
      - if current_user.encrypted_password.blank?
        %li{ class: "#{'active' if request.url == new_users_password_url || request.url == users_password_url}" }
          = link_to t("menu.new_password"), new_users_password_path
      - else
        %li{ class: "#{'active' if request.url == edit_users_password_url || request.url == users_password_url}" }
          = link_to t("menu.edit_password"), edit_users_password_path
      %li{ class: "#{'active' if request.url == edit_users_notification_url}" }
        = link_to Notification.model_name.human, edit_users_notification_path
      %li{ class: "#{'active' if request.url == users_unsubscribe_url}" }
        = link_to t("menu.unsubscribe"), users_unsubscribe_path

app/views/shared/_plan_index_group.html.haml
.plan-group
  - plans.each do |plan|
    .plan-item{ class: "#{"sm-item" if size == "sm"}" }
      = link_to plan do
        .plan-image
          - photo = plan.get_header_image
          = image_tag photo.present? ? photo.image.thumb.url : "no_plan_image.png"
        .plan-info
          .plan-info-right
            .plan-user-image
              = link_to user_profile_path(plan.user.name) do
                = image_tag plan.user.profile_image_thumb_url
          .plan-info-left
            %h3.plan-name= plan.name
            .plan-description
              %p
                = plan.description
            .plan-user-name
              %span by
              = link_to plan.user.display_name, user_profile_path(plan.user.name)
            .plan-reactions
              .plan-pageviews
                = fa_icon "eye"
                = plan.total_pv
              .plan-like
                - if current_user&.likes&.find_by(plan_id: plan).present?
                  = fa_icon "heart"
                - else
                  = fa_icon "heart-o"
                = plan.likes.count
              .plan-comment
                = fa_icon "comment-o"
                = plan.comments.count