config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  devise_for :users, controllers: { 
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  namespace :users do
    resources :plans, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :social_accounts, only: [:destroy]
    resource :profile, only: [:edit, :update]
    resource :notification, only: [:edit, :update]
    resource :password, only: [:new, :create, :edit, :password]
    patch "/password", to: "passwords#update"
    get "/plans_published", to: "plans#published"
    get "/plans_draft", to: "plans#draft"
    get "/suggest_spot", to: "plans#suggest_spot"
    post "/spots", to: "spots#create"
    post "/photos", to: "photos#create"
    get "/unsubscribe", to: "unsubscribe#show"
    patch "/level_up", to: "level_up#update"
    patch "/got_trophy", to: "got_trophy#update"
  end

  resources :users, module: :users, param: :name, path: "/", only: [] do
    resource :profile, only: [:show], controller: "profiles"
    get "/likes", to: "profiles#like"
    get "/trophies", to: "profiles#trophy"
    get "/followers", to: "profiles#followers"
    get "/following", to: "profiles#following"
    resource :relationship, only: [:create, :destroy]
  end

  resources :plans, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get "/search", to: "search#index"
  get "/terms", to: "static#terms"
  get "/privacy_policy", to: "static#privacy_policy"
  post "/opinions", to: "opinions#create"

  namespace :batch do
    resources :save_page_views, only: [:create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  extend Enumerize
  include Redis::Objects

  enumerize :status, in: { draft: 0, published: 1 }, scope: true, predicates: true

  belongs_to :user
  has_many :spots, -> { order(:position) }, inverse_of: :plan, dependent: :destroy
  accepts_nested_attributes_for :spots, reject_if: :all_blank, allow_destroy: true
  has_many :photos, -> { order(:position) }, through: :spots
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :page_views, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 1000 }

  scope :default_order, -> { order(published_at: :desc) }
  scope :management_order, -> { reorder(id: :desc) }
  scope :published, -> { with_status(:published).default_order }
  scope :draft, -> { with_status(:draft).default_order }
  scope :with_popular, lambda {
    plan_ids = self.published.pluck(:id)
    likes = Like.between_1_month.except_plan_user.group(:plan_id).count
    comments = Comment.between_1_month.except_plan_user.group(:plan_id).count
    pvs = PageView.between_1_month.group(:plan_id).sum(:count)
    scores = plan_ids.map do |plan_id|
      like = likes[plan_id].to_i
      comment = comments[plan_id].to_i
      pv = pvs[plan_id].to_i + self.pv[plan_id].to_i
      [plan_id, pv > 0 ? (like * 0.7 + comment * 0.3) / pv : 0]
    end
    ids = scores.to_h.delete_if { |_,v| v == 0 }.sort_by { |_,v| -v }.to_h.keys
    self.where(id: ids).order("field(id, #{ids.present? ? ids.join(',') : 'null'})")
  }

  ransack_alias :keyword, :name_or_description_or_spots_name_or_spots_description_or_spots_address

  def get_header_image
    photos.find_by(is_header: true) || photos.first
  end

  # PV機能の実装
  # 方針: PVの厳密な集計はせずにバッチが走ったタイミングで翌日のPVを集計するようにする
  # 1. 投稿したユーザー以外のPVをredisに格納
  # 2. 溜まったPVをDBに保存する処理を実行
  # 3. 保存処理が完了したらredisののPVをリセットする処理の実行
  #
  sorted_set :pv, global: true

  def increment_pv
    self.class.pv.increment(id)
  end

  def daily_pv
    self.class.pv[id].to_i
  end

  def total_pv
    daily_pv + page_views.sum(:count)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_plan, only: [:show]
  before_action :set_meta

  def index
    case params[:type]
    when "popular"
      @plans = Plan.with_popular.page(params[:page])
    when "following"
      @plans = current_user.following_plans.page(params[:page]) if user_signed_in?
    else
      @plans = Plan.published.page(params[:page])
    end
  end

  def show
    @user = @plan.user
    return redirect_to root_path if @plan.draft? && @user != current_user

    @plan.increment_pv if @user != current_user
    @user.trophy.judge_pv_count!

    @photo = @plan.get_header_image
    @like = @plan.likes.find_by(user: current_user)
    @comment = current_user&.comments&.build
    @comments = @plan.comments
  end

  private

    def set_plan
      @plan = Plan.find(params[:id])
    end

    def set_meta
      case action_name
      when "index" then
        title = params[:type] == "popular" ? t(".popular_plans") : t(".latest_plans")
        set_common_meta(:title, title)
      when "show" then
        set_common_meta(:title, @plan.name)
        set_common_meta(:description, @plan.description)
        set_common_meta(:image, @plan.get_header_image.image.url) if @plan.get_header_image.present?
        set_meta_tags keyword: @plan.spots.map(&:name).join(", ")
      end
    end
end

app/controllers/users/plans_controller.rb
class Users::PlansController < ApplicationController
  before_action :set_plan, only: [:edit, :update, :destroy]
  before_action :is_current_user?, only: [:edit, :update, :destroy]

  def index
    @plans = current_user.plans.management_order.page(params[:page])
    respond_to do |format|
      format.html
      format.js { render "plan_list" }
    end
  end

  def published
    @plans = current_user.plans.published.management_order.page(params[:page])
    respond_to do |format|
      format.js { render "plan_list" }
    end
  end

  def draft
    @plans = current_user.plans.draft.management_order.page(params[:page])
    respond_to do |format|
      format.js { render "plan_list" }
    end
  end

  def new
    @plan = current_user.plans.build
  end

  def create
    @plan = current_user.plans.build(new_plan_params)
    if @plan.save
      redirect_to edit_users_plan_path(@plan, init: true)
    else
      render "new"
    end
  end

  def edit
    @plan.spots.create if @plan.spots.blank?
  end

  def update
    if params[:published]
      @plan.status = :published
      @plan.published_at = Time.zone.now if @plan.published_at.blank?
    elsif params[:draft]
      @plan.status = :draft
    end

    if @plan.update(edit_plan_params)
      if params[:sortable]
        redirect_to edit_users_plan_path(@plan), notice: t(:sort_success, scope: :flash)
      else
        RefreshSitemapJob.perform_later
        current_user.obtain_exp!
        current_user.trophy.judge_plan_count!
        redirect_to plan_path(@plan), notice: t(:update_success, scope: :flash)
      end
    else
      flash.now[:alert] = t(:register_failed, scope: :flash)
      render "edit"
    end
  end

  def destroy
    @plan.destroy!
    @plan.user.obtain_exp!
    redirect_to users_plans_path, notice: t(:delete_success, scope: :flash)
  end

  def suggest_spot
    key = Rails.configuration.x.google_apis[:map]
    input = params[:input]

    # オートコンプリート用のクエリ
    url = "https://maps.googleapis.com/maps/api/place/autocomplete/json?"
    params = URI.encode_www_form({ key: key, input: input, language: :ja})
    uri = URI.parse "#{url}#{params}"

    request = Net::HTTP::Get.new(uri.request_uri)
    response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") do |http|
      http.request(request)
    end

    body = JSON.load response.body
    places = body["predictions"].map do |item|
      {
        place_id: item.dig("place_id"),
        name: item.dig("structured_formatting", "main_text"),
        address: item.dig("structured_formatting", "secondary_text"),
      }
    end

    render json: places
  end

  private

    def new_plan_params
      params.require(:plan).permit(:name, :description)
    end

    def edit_plan_params
      params.require(:plan).permit(:name, :description, spots_attributes: [:id, :name, :description, :address, :latitude, :longitude, :position, :_destroy, photos_attributes: [:id, :position, :is_header, :_destroy]])
    end

    def set_plan
      @plan = current_user.plans.find(params[:id])
    end

    def is_current_user?
      redirect_to root_path unless @plan.user == current_user
    end
end

app/views/plans/_form.html.haml
= simple_form_for @plan do |f|
  - if @plan.errors.present?
    - @plan.errors.full_messages.each do |msg|
      = msg
  = f.input :name
  = f.input :description, input_html: { rows:5 }
  %h2= t("title.register_spot")
  .spot_container
    = f.simple_fields_for :spots do |spot|
      = render "spot_fields", f: spot
    .links
      = link_to_add_association f, :spots, class: "btn btn-success"
  = f.button :submit, t("link.published"), class: "btn-primary"
  = f.button :submit, t("link.draft"), class: "btn-primary", name: :draft

app/views/plans/_like.html.haml
.like
  = link_to likes_path(plan_id: @plan.id), method: :post, remote: true do
    = fa_icon "heart-o"
    = Like.where(plan_id: @plan).count

app/views/plans/_photo_grid.html.haml
- photos_length = spot.photos.length
.grid-container.pop-up-image{ class: "grid-style-#{photos_length < 5 ? photos_length : 5}" }
  - spot.photos.each.with_index(1) do |photo, i|
    = link_to "", photo.image.url, class: "grid-item", style: "background-image: url(#{photo.image.thumb.url});"
    - break if i == 4
  - if photos_length >= 5
    = link_to spot.photos[4].image.url, class: "grid-item", style: "background-image: url(#{spot.photos[4].image.thumb.url});" do
      - if photos_length > 5
        .gray-back
          .more-image= "+#{photos_length - 5}"
    - spot.photos[5..(photos_length - 1)].each do |photo|
      = link_to "", photo.image.url, style: "display: none;"

app/views/plans/_unlike.html.haml
.unlike
  = link_to like_path(@plan), method: :delete, remote: true do
    = fa_icon "heart"
    = Like.where(plan_id: @plan).count

app/views/plans/index.html.haml
.container
  .plan-index-area
    .plan-index-group
      %h2= params[:type] == "popular" ? t(".popular_plans") : t(".latest_plans")
      - if @plans.present?
        = render "shared/plan_index_group", plans: @plans, size: "lg"
        = paginate @plans, params: { type: params[:type] == "popular" ? :popular : :latest }
      - else
        = t("view.no_plans")

app/views/plans/show.html.haml
.plan-top
  - if @photo.present?
    .plan-top-image{ style: "background-image: url(#{@photo.image.url})" }
  - else
    .no-plan-top-image
.container
  .row
    .main-field.col-md-9
      .plan-field
        .plan-header
          %h2.plan-name= @plan.name
          .plan-description= simple_format h(@plan.description)
          .top-author-field
            = link_to user_profile_path(@user.name), class: "author-image" do
              = image_tag @user.profile.thumb_url
            = link_to user_profile_path(@user.name), class: "author-name" do
              = @user.display_name
          - if @plan.published?
            .top-reaction-field
              .pageviews
                = fa_icon "eye"
                = @plan.total_pv
              .like-area
                - if user_signed_in?
                  - if @like.present?
                    = render "plans/unlike"
                  - else
                    = render "plans/like"
                - else
                  .like
                    = link_to new_user_session_path do
                      = fa_icon "heart-o"
                      = Like.where(plan_id: @plan).count
              .comment
                = link_to "#comment-field", class: "smooth-scroll"  do
                  = fa_icon "comment-o"
                  = Comment.where(plan_id: @plan).count
          - if @plan.user == current_user
            .plan-menu
              = link_to t("link.edit"), edit_users_plan_path(@plan), class: "btn btn-success"
              = link_to t("link.delete"), users_plan_path(@plan), method: :delete, data: { confirm: t("view.delete_confirm") }, class: "btn btn-danger"
          .clear
        .spot-field
          - @plan.spots.each_with_index do |spot, i|
            .spot-item{ id: "spot-#{spot.position}" }
              = hidden_field_tag :latitude, spot.latitude, class: "spot-latitude"
              = hidden_field_tag :longitude, spot.longitude, class: "spot-longitude"
              = hidden_field_tag :position, spot.position, class: "spot-position"
              %h2.spot-header
                .spot-position-num= spot.position
                .spot-name= spot.name
              - if spot.photos.any?
                .image-area
                  = render "plans/photo_grid", spot: spot
              .spot-description= simple_format h(spot.description)
          - lat_length = @plan.spots.map { |spot| spot.latitude }.compact.length
          - if lat_length > 1
            #route-map.map
        - if @plan.published?
          .bottom-reaction-field
            .plan-reaction
              .pageviews
                = fa_icon "eye"
                = @plan.total_pv
              .like-area
                - if user_signed_in?
                  - if @like.present?
                    = render "plans/unlike"
                  - else
                    = render "plans/like"
                - else
                  .like
                    = link_to new_user_session_path do
                      = fa_icon "heart-o"
                      = Like.where(plan_id: @plan).count
              .comment
                = link_to "#comment-field", class: "smooth-scroll"  do
                  = fa_icon "comment-o"
                  = Comment.where(plan_id: @plan).count
            .sns-reaction.set-open-new-window
              .sns-share-btn
                = link_to "https://twitter.com/share?url=#{plan_url(@plan)}", class: "btn btn-twitter open-new-window" do
                  = fa_icon "twitter"
                  = t(".share_twitter")
              .sns-share-btn
                = link_to "https://www.facebook.com/sharer/sharer.php?u=#{plan_url(@plan)}", class: "btn btn-facebook open-new-window" do
                  = fa_icon "facebook"
                  = t(".share_facebook")
              .sns-share-btn
                = link_to "https://social-plugins.line.me/lineit/share?url=#{plan_url(@plan)}", class: "btn btn-line open-new-window" do
                  = fa_icon "comment"
                  = t(".share_line")
        .bottom-author-field
          .author-info-left
            = link_to user_profile_path(@user.name) do
              .author-image= image_tag @user.profile.thumb_url
          .author-info-right
            = link_to user_profile_path(@user.name) do
              .author-name= "#{@user.display_name}　Lv.#{@user.level}"
            .author-description= @user.profile.description
      #comment-field.comment-field
        - @comments.each do |comment|
          .comment-item
            .comment-header
              = link_to user_profile_path(comment.user.name), class: "comment-user" do
                .comment-user-image= image_tag comment.user.profile.thumb_url
                .comment-user-name= comment.user.display_name
              .comment-at= comment.created_at.strftime("%Y-%m-%d %H:%M")
            .comment-content= simple_format h(comment.content)
            -if current_user == comment.user
              .comment-delete= link_to t("link.delete"), comment_path(comment), method: :delete, data: { confirm: t("view.delete_confirm") }
        -if user_signed_in? && @plan.published?
          = simple_form_for @comment do |f|
            = f.hidden_field :plan_id, value: @plan.id
            = f.input :content, required: false, placeholder: t("form.input_comment"), input_html: { rows: 3 }, label: t("form.label_comment")
            = f.button :submit, value: t("form.submit_comment"), class: "btn-success"
    .sidebar.col-md-3
      .following-scroll
        %ul.table-contents
          %li.table-contents-header= t("view.spot_table_contents")
          - @plan.spots.each do |spot|
            = link_to "#spot-#{spot.position}", class: "table-contents-item smooth-scroll page-link" do
              %li
                .table-contents-position= spot.position
                .table-contents-name= spot.name
          - if lat_length > 1
            = link_to "#route-map", class: "table-contents-item smooth-scroll page-link" do
              .table-contents-icon= fa_icon "map"
              .table-contents-name= t("view.route_map")